//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taobao.Workflow.Activities.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taobao.Workflow.Activities.Test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;activities&gt;
        ///  &lt;flowinfo name=&quot;VPNRequest&quot; group=&quot;VPN账号申请流程&quot; version=&quot;20111108105943&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[安全管理]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;/flow/task.aspx&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///      &lt;action&gt;&lt;![CDATA[否决]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivitySettingsDefinitionNew1 {
            get {
                return ResourceManager.GetString("ActivitySettingsDefinitionNew1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;Human&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;s&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[vvv]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[getSuperiors(&apos;&apos;,0,0)]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;无&quot;&gt;&lt;![CDATA[]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivitySettingsDefinitionNew4 {
            get {
                return ResourceManager.GetString("ActivitySettingsDefinitionNew4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;Human&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;aspx&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;无&quot;&gt;&lt;![CDATA[]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalation expir [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppendHumanActivity_Settings {
            get {
                return ResourceManager.GetString("AppendHumanActivity_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;aspx&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[user]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;完成&quot;&gt;&lt;![CDATA[true [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppendHumanActivity_Settings_Wrong {
            get {
                return ResourceManager.GetString("AppendHumanActivity_Settings_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables&gt;
        ///    &lt;Variable Name=&quot;UserName1&quot; Value=&quot;&quot; Mode=&quot;flow&quot; /&gt;
        ///    &lt;Variable Name=&quot;UserName2&quot; Value=&quot;&quot; Mode=&quot;flow&quot; /&gt;
        ///    &lt;Variable Name=&quot;webroot&quot; Value=&quot;http://wf.taobao.org&quot; Mode=&quot;design&quot; /&gt;
        ///  &lt;/Variables&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;695 64&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;675 174&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;676 257&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;LinkData From [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppendHumanActivity_Workflow {
            get {
                return ResourceManager.GetString("AppendHumanActivity_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables&gt;
        ///    &lt;Variable Name=&quot;user&quot; Value=&quot;&quot; /&gt;
        ///  &lt;/Variables&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;290 104&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;292 187&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 3&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;290 288&quot; Text=&quot;节点3&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 4&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppendHumanActivity_Workflow_Wrong {
            get {
                return ResourceManager.GetString("AppendHumanActivity_Workflow_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;wwww&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;同意&quot;&gt;&lt;![CDATA[all(&quot;同意&quot;)]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientTest2_Settings {
            get {
                return ResourceManager.GetString("ClientTest2_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables /&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;285 140&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;LinkData From=&quot;Start&quot; To=&quot;Human&quot; IsDefault=&quot;true&quot; /&gt;
        ///&lt;/FlowChart&gt;.
        /// </summary>
        internal static string ClientTest2_Workflow {
            get {
                return ResourceManager.GetString("ClientTest2_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///    &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///      &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///    &lt;/flowinfo&gt;
        ///    &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;www&quot;&gt;
        ///      &lt;actions&gt;
        ///        &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///        &lt;action&gt;&lt;![CDATA[否决]]&gt;&lt;/action&gt;
        ///      &lt;/actions&gt;
        ///      &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///      &lt;actioners&gt;
        ///        &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///      &lt;/actioners&gt;
        ///      &lt;finish&gt;
        ///        &lt;line na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTFE_UnitTest1_Settings {
            get {
                return ResourceManager.GetString("NTFE_UnitTest1_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables&gt;
        ///    &lt;Variable Name=&quot;UserName1&quot; Value=&quot;&quot; /&gt;
        ///    &lt;Variable Name=&quot;UserName2&quot; Value=&quot;&quot; /&gt;
        ///  &lt;/Variables&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;287 168&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;55 278&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Server&quot; Category=&quot;Server&quot; IsSubGraph=&quot;true&quot; Location=&quot;422 280&quot; Text=&quot;自动节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Chil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTFE_UnitTest1_Worflow {
            get {
                return ResourceManager.GetString("NTFE_UnitTest1_Worflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///    &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///      &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///    &lt;/flowinfo&gt;
        ///    &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;www&quot;&gt;
        ///      &lt;actions&gt;
        ///        &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///        &lt;action&gt;&lt;![CDATA[否决]]&gt;&lt;/action&gt;
        ///      &lt;/actions&gt;
        ///      &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///      &lt;actioners&gt;
        ///        &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///      &lt;/actioners&gt;
        ///      &lt;finish&gt;
        ///        &lt;line na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTFE_UnitTest2_Settings {
            get {
                return ResourceManager.GetString("NTFE_UnitTest2_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables&gt;
        ///    &lt;Variable Name=&quot;username1&quot; Value=&quot;&quot; /&gt;
        ///  &lt;/Variables&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;287 141&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;70 316&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Server&quot; Category=&quot;Server&quot; IsSubGraph=&quot;true&quot; Location=&quot;485 328&quot; Text=&quot;节点3&quot; /&gt;
        ///  &lt;NodeData Key=&quot;ParallelContainer&quot; Category=&quot;ParallelContainer&quot; Is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTFE_UnitTest2_Workflow {
            get {
                return ResourceManager.GetString("NTFE_UnitTest2_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;www&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[确认]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;确认&quot;&gt;&lt;![CDATA[all(&quot;确认&quot;)]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTFE_UnitTest3_Settings {
            get {
                return ResourceManager.GetString("NTFE_UnitTest3_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables /&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;283 165&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;279 311&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;LinkData From=&quot;Start&quot; To=&quot;Human&quot; IsDefault=&quot;true&quot; /&gt;
        ///  &lt;LinkData From=&quot;Human&quot; To=&quot;Human 2&quot; Text=&quot;确认&quot; IsDefault=&quot;false&quot; /&gt;
        ///&lt;/FlowChart&gt;.
        /// </summary>
        internal static string NTFE_UnitTest3_Workflow {
            get {
                return ResourceManager.GetString("NTFE_UnitTest3_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;www&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[确认]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;确认&quot;&gt;&lt;![CDATA[all(&quot;确认&quot;)]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTFE_UnitTest4_Settings {
            get {
                return ResourceManager.GetString("NTFE_UnitTest4_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables /&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;283 165&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;279 311&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;LinkData From=&quot;Start&quot; To=&quot;Human&quot; IsDefault=&quot;true&quot; /&gt;
        ///  &lt;LinkData From=&quot;Human&quot; To=&quot;Human 2&quot; Text=&quot;确认&quot; IsDefault=&quot;false&quot; /&gt;
        ///&lt;/FlowChart&gt;.
        /// </summary>
        internal static string NTFE_UnitTest4_Workflow {
            get {
                return ResourceManager.GetString("NTFE_UnitTest4_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;www&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[确认]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;确认&quot;&gt;&lt;![CDATA[all(&quot;确认&quot;)]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTFE_UnitTest5_Settings {
            get {
                return ResourceManager.GetString("NTFE_UnitTest5_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables /&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;283 165&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;279 311&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;LinkData From=&quot;Start&quot; To=&quot;Human&quot; IsDefault=&quot;true&quot; /&gt;
        ///  &lt;LinkData From=&quot;Human&quot; To=&quot;Human 2&quot; Text=&quot;确认&quot; IsDefault=&quot;false&quot; /&gt;
        ///&lt;/FlowChart&gt;.
        /// </summary>
        internal static string NTFE_UnitTest5_Workflow {
            get {
                return ResourceManager.GetString("NTFE_UnitTest5_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;www&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[完成]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[getSuperiors(&apos;&apos;,0,0)]]&gt;&lt;/actioner&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;完成 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTFE_UnitTest6_Settings {
            get {
                return ResourceManager.GetString("NTFE_UnitTest6_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables /&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;288 137&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;287 283&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;LinkData From=&quot;Start&quot; To=&quot;Human&quot; IsDefault=&quot;true&quot; /&gt;
        ///  &lt;LinkData From=&quot;Human&quot; To=&quot;Human 2&quot; Text=&quot;完成&quot; IsDefault=&quot;false&quot; /&gt;
        ///&lt;/FlowChart&gt;.
        /// </summary>
        internal static string NTFE_UnitTest6_Workflow {
            get {
                return ResourceManager.GetString("NTFE_UnitTest6_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;activities&gt;
        ///  &lt;flowinfo name=&quot;ClientTest&quot; group=&quot;测试&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[Test]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;/flow/task.aspx&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;Default&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings4 {
            get {
                return ResourceManager.GetString("Settings4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;activities&gt;
        ///  &lt;flowinfo name=&quot;ClientTest&quot; group=&quot;测试&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[Test]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;/flow/task.aspx&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///      &lt;action&gt;&lt;![CDATA[RuntimeAppendedAction]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;Default&quot; unlimited=&quot;true&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[origina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings5 {
            get {
                return ResourceManager.GetString("Settings5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;activities&gt;
        ///  &lt;flowinfo name=&quot;ClientTest&quot; group=&quot;测试&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[Test]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;/flow/task.aspx&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings7 {
            get {
                return ResourceManager.GetString("Settings7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;wwww&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;同意&quot;&gt;&lt;![CDATA[all(&quot;同意&quot;)]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitTestTypeParentProcess_Settings {
            get {
                return ResourceManager.GetString("UnitTestTypeParentProcess_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables /&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;285 140&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 3&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;285 445&quot; Text=&quot;节点3&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 4&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;284 548&quot; Text=&quot;节点4&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Child&quot; Category=&quot;Child&quot; IsSubGraph=&quot;true&quot; Location=&quot;286 289&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;LinkData From=&quot;Start&quot; To=&quot;Hu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitTestTypeParentProcess_Workflow {
            get {
                return ResourceManager.GetString("UnitTestTypeParentProcess_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activities&gt;
        ///  &lt;flowinfo name=&quot;&quot; group=&quot;&quot; version=&quot;&quot;&gt;
        ///    &lt;description&gt;&lt;![CDATA[]]&gt;&lt;/description&gt;
        ///  &lt;/flowinfo&gt;
        ///  &lt;human name=&quot;节点1&quot; isChildOfActivity=&quot;false&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;wwww&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; unlimited=&quot;false&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;同意&quot;&gt;&lt;![CDATA[all(&quot;同意&quot;)]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitTestTypeSubProcess_Settings {
            get {
                return ResourceManager.GetString("UnitTestTypeSubProcess_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables /&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;285 140&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;285 298&quot; Text=&quot;节点2&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Server&quot; Category=&quot;Server&quot; IsSubGraph=&quot;true&quot; Location=&quot;283 450&quot; Text=&quot;节点3&quot; /&gt;
        ///  &lt;LinkData From=&quot;Start&quot; To=&quot;Human&quot; IsDefault=&quot;true&quot; /&gt;
        ///  &lt;LinkData From=&quot;Human&quot; To=&quot;Human 2&quot; Text=&quot;同意&quot; IsDefault=&quot;false&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitTestTypeSubProcess_Workflow {
            get {
                return ResourceManager.GetString("UnitTestTypeSubProcess_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Activity mc:Ignorable=&quot;sap&quot; x:Class=&quot;Taobao.Workflow.Activities.Designer.Templates.Blank&quot; sap:VirtualizedContainerService.HintSize=&quot;654,676&quot; mva:VisualBasic.Settings=&quot;Assembly references and imported namespaces for internal implementation&quot; xmlns=&quot;http://schemas.microsoft.com/netfx/2009/xaml/activities&quot; xmlns:av=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:mv=&quot;clr-namespace:Microsoft.VisualBasic;assembly=System&quot; xmln [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkflowDefinition1 {
            get {
                return ResourceManager.GetString("WorkflowDefinition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Activity mc:Ignorable=&quot;sap&quot; x:Class=&quot;Taobao.Workflow.Activities.Designer.Templates.Blank&quot; sap:VirtualizedContainerService.HintSize=&quot;654,676&quot; mva:VisualBasic.Settings=&quot;Assembly references and imported namespaces for internal implementation&quot; xmlns=&quot;http://schemas.microsoft.com/netfx/2009/xaml/activities&quot; xmlns:av=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:mv=&quot;clr-namespace:Microsoft.VisualBasic;assembly=System&quot; xmln [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkflowDefinition4 {
            get {
                return ResourceManager.GetString("WorkflowDefinition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Activity mc:Ignorable=&quot;sap&quot; x:Class=&quot;Taobao.Workflow.Activities.Designer.Templates.Blank&quot; sap:VirtualizedContainerService.HintSize=&quot;654,676&quot; mva:VisualBasic.Settings=&quot;Assembly references and imported namespaces for internal implementation&quot; xmlns=&quot;http://schemas.microsoft.com/netfx/2009/xaml/activities&quot; xmlns:av=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:mv=&quot;clr-namespace:Microsoft.VisualBasic;assembly=System&quot; xmln [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkflowDefinition5 {
            get {
                return ResourceManager.GetString("WorkflowDefinition5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Activity mc:Ignorable=&quot;sap&quot; x:Class=&quot;Taobao.Workflow.Activities.Designer.Templates.Blank&quot; sap:VirtualizedContainerService.HintSize=&quot;654,676&quot; mva:VisualBasic.Settings=&quot;Assembly references and imported namespaces for internal implementation&quot; xmlns=&quot;http://schemas.microsoft.com/netfx/2009/xaml/activities&quot; xmlns:av=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:mv=&quot;clr-namespace:Microsoft.VisualBasic;assembly=System&quot; xmln [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkflowDefinition7 {
            get {
                return ResourceManager.GetString("WorkflowDefinition7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables&gt;
        ///    &lt;Variable Name=&quot;username1&quot; Value=&quot;&quot; /&gt;
        ///  &lt;/Variables&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;308 0&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;__ReferenceID0&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;270 172.5&quot; Text=&quot;节点1&quot; /&gt;
        ///  &lt;LinkData From=&quot;__ReferenceID0&quot; To=&quot;__ReferenceID1&quot; Text=&quot;同意&quot; IsDefault=&quot;false&quot; /&gt;
        ///  &lt;LinkData From=&quot;__ReferenceID0&quot; To=&quot;__ReferenceID2&quot; Text=&quot;否决&quot; IsDefault=&quot;false&quot; /&gt;
        ///  &lt;NodeData Key=&quot;__ReferenceID1&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Locat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkflowDefinitionNew1 {
            get {
                return ResourceManager.GetString("WorkflowDefinitionNew1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowChart&gt;
        ///  &lt;Variables /&gt;
        ///  &lt;NodeData Key=&quot;Start&quot; Category=&quot;Start&quot; Location=&quot;245 15&quot; Text=&quot;Start&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human&quot; Category=&quot;Human&quot; IsSubGraph=&quot;true&quot; Location=&quot;384 352&quot; Text=&quot;Human&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Server&quot; Category=&quot;Server&quot; IsSubGraph=&quot;true&quot; Location=&quot;-19 146&quot; Text=&quot;Server&quot; /&gt;
        ///  &lt;NodeData Key=&quot;ParallelContainer&quot; Category=&quot;ParallelContainer&quot; IsSubGraph=&quot;true&quot; Location=&quot;-63 530&quot; Text=&quot;ParallelContainer&quot; /&gt;
        ///  &lt;NodeData Key=&quot;Human 2&quot; Category=&quot;HumanPar&quot; IsSubGraph=&quot;true&quot; SubGraphKey=&quot;Paral [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkflowDefinitionNew4 {
            get {
                return ResourceManager.GetString("WorkflowDefinitionNew4", resourceCulture);
            }
        }
    }
}
