//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Host.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taobao.Workflow.Host.Test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;activities&gt;
        ///  &lt;human name=&quot;节点1&quot; slot=&quot;-1&quot; url=&quot;www.taobao.com&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///      &lt;action&gt;&lt;![CDATA[否决]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[getSuperior()]]&gt;&lt;/actioner&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;同意&quot;&gt;&lt;![CDATA[all(&quot;同意&quot;)]]&gt;&lt;/line&gt;
        ///      &lt;line name=&quot;否决&quot;&gt;&lt;![CDATA[atMostOf(1,&apos;否决&apos;)]]&gt;&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;activities&gt;
        ///  &lt;human name=&quot;节点1&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;www&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///      &lt;action&gt;&lt;![CDATA[否决]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;同意&quot;&gt;&lt;![CDATA[all(&quot;同意&quot;)]]&gt;&lt;/line&gt;
        ///      &lt;line name=&quot;否决&quot;&gt;&lt;![CDATA[all(&quot;否决&quot;)]]&gt;&lt;/line&gt;
        ///    &lt;/finish&gt;
        ///    &lt;escalation /&gt;
        ///  &lt;/human [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings1 {
            get {
                return ResourceManager.GetString("Settings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;activities&gt;
        ///  &lt;human name=&quot;节点1&quot; slot=&quot;-1&quot; slotMode=&quot;allAtOnce&quot; url=&quot;www&quot;&gt;
        ///    &lt;actions&gt;
        ///      &lt;action&gt;&lt;![CDATA[同意]]&gt;&lt;/action&gt;
        ///      &lt;action&gt;&lt;![CDATA[否决]]&gt;&lt;/action&gt;
        ///    &lt;/actions&gt;
        ///    &lt;start at=&quot;&quot; after=&quot;&quot; zone=&quot;&quot; /&gt;
        ///    &lt;actioners&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[getSuperior()]]&gt;&lt;/actioner&gt;
        ///      &lt;actioner&gt;&lt;![CDATA[originator]]&gt;&lt;/actioner&gt;
        ///    &lt;/actioners&gt;
        ///    &lt;finish&gt;
        ///      &lt;line name=&quot;同意&quot;&gt;&lt;![CDATA[all(&apos;同意&apos;)]]&gt;&lt;/line&gt;
        ///      &lt;line name=&quot;否决&quot;&gt;&lt;![CDATA[atMostOf(1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings2 {
            get {
                return ResourceManager.GetString("Settings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Activity mc:Ignorable=&quot;sap&quot; x:Class=&quot;Taobao.Workflow.Activities.Designer.Templates.Blank&quot; sap:VirtualizedContainerService.HintSize=&quot;654,676&quot; mva:VisualBasic.Settings=&quot;Assembly references and imported namespaces for internal implementation&quot; xmlns=&quot;http://schemas.microsoft.com/netfx/2009/xaml/activities&quot; xmlns:av=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:mv=&quot;clr-namespace:Microsoft.VisualBasic;assembly=System&quot; xmln [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Activity mc:Ignorable=&quot;sap&quot; x:Class=&quot;Taobao.Workflow.Activities.Designer.Templates.Blank&quot; sap:VirtualizedContainerService.HintSize=&quot;654,676&quot; mva:VisualBasic.Settings=&quot;Assembly references and imported namespaces for internal implementation&quot; xmlns=&quot;http://schemas.microsoft.com/netfx/2009/xaml/activities&quot; xmlns:av=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:mv=&quot;clr-namespace:Microsoft.VisualBasic;assembly=System&quot; xmln [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Workflow1 {
            get {
                return ResourceManager.GetString("Workflow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Activity mc:Ignorable=&quot;sap&quot; x:Class=&quot;Taobao.Workflow.Activities.Designer.Templates.Blank&quot; sap:VirtualizedContainerService.HintSize=&quot;654,676&quot; mva:VisualBasic.Settings=&quot;Assembly references and imported namespaces for internal implementation&quot; xmlns=&quot;http://schemas.microsoft.com/netfx/2009/xaml/activities&quot; xmlns:av=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:mv=&quot;clr-namespace:Microsoft.VisualBasic;assembly=System&quot; xmln [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Workflow2 {
            get {
                return ResourceManager.GetString("Workflow2", resourceCulture);
            }
        }
    }
}
